# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dfs.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 525)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Filename = QtWidgets.QLabel(self.centralwidget)
        self.Filename.setObjectName("Filename")
        self.horizontalLayout.addWidget(self.Filename)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setObjectName("Title")
        self.horizontalLayout_4.addWidget(self.Title)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.Writes = QtWidgets.QLabel(self.centralwidget)
        self.Writes.setObjectName("Writes")
        self.horizontalLayout_5.addWidget(self.Writes)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.Size = QtWidgets.QLabel(self.centralwidget)
        self.Size.setObjectName("Size")
        self.horizontalLayout_6.addWidget(self.Size)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.BootOption = QtWidgets.QLabel(self.centralwidget)
        self.BootOption.setObjectName("BootOption")
        self.horizontalLayout_7.addWidget(self.BootOption)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.catalogue = QtWidgets.QTableWidget(self.centralwidget)
        self.catalogue.setColumnCount(8)
        self.catalogue.setObjectName("catalogue")
        self.catalogue.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.catalogue.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.catalogue.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.catalogue.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.catalogue.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.catalogue.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.catalogue.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.catalogue.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.catalogue.setHorizontalHeaderItem(7, item)
        self.verticalLayout_2.addWidget(self.catalogue)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Disc_Image = QtWidgets.QAction(MainWindow)
        self.actionOpen_Disc_Image.setObjectName("actionOpen_Disc_Image")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionOpen_Disc_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.actionOpen_Disc_Image.triggered.connect(MainWindow.browseSlot)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DFS Explorer"))
        self.label.setText(_translate("MainWindow", "File Name"))
        self.Filename.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "Disc Title"))
        self.Title.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "Disc Writes"))
        self.Writes.setText(_translate("MainWindow", "Disc Writes"))
        self.label_11.setText(_translate("MainWindow", "Disc Size"))
        self.Size.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "Boot Option"))
        self.BootOption.setText(_translate("MainWindow", "TextLabel"))
        item = self.catalogue.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Directory"))
        item = self.catalogue.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.catalogue.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Load Address"))
        item = self.catalogue.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Exec Address"))
        item = self.catalogue.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Length"))
        item = self.catalogue.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Locked"))
        item = self.catalogue.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Save"))
        item = self.catalogue.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Display"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Disc_Image.setText(_translate("MainWindow", "Open Disc Image"))
        self.actionOpen_Disc_Image.setStatusTip(_translate("MainWindow", "Open a disc image"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Exit the application."))
